<a href="https://colab.research.google.com/github/Saumya731/AI-Research-Power-Intelligent-System/blob/main/Project__2_AI_Research_Power_Intelligent_System_project_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q datasets
!pip install -q sentence-transformers
!pip install -q faiss-cpu
!pip install -q transformers
!pip install -q pandas
!pip install -q numpy
!pip install -q torch
!pip install -q scikit-learn

In [ ]:
import pandas as pd
import numpy as np
import torch
import faiss

from datasets import load_dataset

from sentence_transformers import SentenceTransformer

from transformers import pipeline

from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
dataset = load_dataset(
    "CShorten/ML-ArXiv-Papers",
    split="train"
)

print(dataset)

README.md:   0%|          | 0.00/986 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

ML-Arxiv-Papers.csv:   0%|          | 0.00/147M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/117592 [00:00<?, ? examples/s]

Dataset({
    features: ['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'],
    num_rows: 117592
})

In [ ]:
dataset = load_dataset(
    "CShorten/ML-ArXiv-Papers",
    split="train"
)

print(dataset)

Dataset({
    features: ['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'],
    num_rows: 117592
})

In [ ]:
df = dataset.to_pandas()

df.head()

,Unnamed: 0.1,Unnamed: 0,title,abstract
0,0,0.0,Learning from compressed observations,The problem of statistical learning is to co...
1,1,1.0,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,2,2.0,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,3,3.0,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,4,4.0,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...

In [ ]:
df = df[['title','abstract']]

df.dropna(inplace=True)

df.reset_index(drop=True,inplace=True)

print(df.shape)

df.head()

(117592, 2)

,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to co...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...

In [ ]:
for i in range(5):

    print("="*100)

    print("Title:\n")

    print(df.iloc[i]['title'])

    print()

    print("Abstract:\n")

    print(df.iloc[i]['abstract'][:500])

====================================================================================================
Title:

Learning from compressed observations

Abstract:

  The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to approach
asymptotically the performance (expected loss) of the best predictor in the
class. We consider the setting in which one has perfect observation of the
$X$-part of the sample, while the $Y$-part
====================================================================================================
Title:

Sensor Networks with Random Links: Topology Design for Distributed
  Consensus

Abstract:

  In a sensor network, in practice, the communication among sensors is subject
to:(1) errors or failures at random times; (3) costs; and(2) constraints since
sensors and networks operate under scarce resources, such as power, data rate,
or communication. The signal-to-noise ratio (SNR) is usually a main factor in
determining the probability of error (or of communication failure) in a link.
These probabilities are then a proxy for the SNR under which the links operate.
The paper studies the probl
====================================================================================================
Title:

The on-line shortest path problem under partial monitoring

Abstract:

  The on-line shortest path problem is considered under various models of
partial monitoring. Given a weighted directed acyclic graph whose edge weights
can change in an arbitrary (adversarial) way, a decision maker has to choose in
each round of a game a path between two distinguished vertices such that the
loss of the chosen path (defined as the sum of the weights of its composing
edges) be as small as possible. In a setting generalizing the multi-armed
bandit problem, after choosing a path, t
====================================================================================================
Title:

A neural network approach to ordinal regression

Abstract:

  Ordinal regression is an important type of learning, which has properties of
both classification and regression. Here we describe a simple and effective
approach to adapt a traditional neural network to learn ordinal categories. Our
approach is a generalization of the perceptron method for ordinal regression.
On several benchmark datasets, our method (NNRank) outperforms a neural network
classification method. Compared with the ordinal regression methods using
Gaussian processes and support ve
====================================================================================================
Title:

Parametric Learning and Monte Carlo Optimization

Abstract:

  This paper uncovers and explores the close relationship between Monte Carlo
Optimization of a parametrized integral (MCO), Parametric machine-Learning
(PL), and `blackbox' or `oracle'-based optimization (BO). We make four
contributions. First, we prove that MCO is mathematically identical to a broad
class of PL problems. This identity potentially provides a new application
domain for all broadly applicable PL techniques: MCO. Second, we introduce
immediate sampling, a new version of the Probab

In [ ]:
model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

print("Model Loaded Successfully")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Model Loaded Successfully

In [ ]:
papers = df['abstract'].tolist()[:5000]

embeddings = model.encode(
    papers,
    batch_size=32,
    show_progress_bar=True,
    convert_to_numpy=True
)

print(embeddings.shape)

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

(5000, 384)

In [ ]:
embeddings = np.asarray(
    embeddings,
    dtype=np.float32
)

print(embeddings.shape)

(5000, 384)

In [ ]:
dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(embeddings)

print("FAISS Index Created Successfully")

print(index.ntotal)

FAISS Index Created Successfully
5000

In [ ]:
faiss.write_index(
    index,
    "research_index.faiss"
)

print("Index Saved")

Index Saved

In [ ]:
def search_paper(query, top_k=5):

    query_embedding = model.encode(
        [query],
        convert_to_numpy=True
    ).astype(np.float32)

    distances, indices = index.search(
        query_embedding,
        top_k
    )

    for rank, idx in enumerate(indices[0]):

        print("="*100)

        print("Rank:", rank+1)

        print()

        print("Title:\n")

        print(df.iloc[idx]["title"])

        print()

        print("Abstract:\n")

        print(df.iloc[idx]["abstract"][:700])

        print()

        print("Distance:", distances[0][rank])

In [ ]:
search_paper("Deep Learning for Image Classification")

====================================================================================================
Rank: 1

Title:

Unsupervised feature learning by augmenting single images

Abstract:

  When deep learning is applied to visual object recognition, data augmentation
is often used to generate additional training data without extra labeling cost.
It helps to reduce overfitting and increase the performance of the algorithm.
In this paper we investigate if it is possible to use data augmentation as the
main component of an unsupervised feature learning architecture. To that end we
sample a set of random image patches and declare each of them to be a separate
single-image surrogate class. We then extend these trivial one-element classes
by applying a variety of transformations to the initial 'seed' patches. Finally
we train a convolutional neural network to discriminate between t

Distance: 0.8688776
====================================================================================================
Rank: 2

Title:

Deeply Coupled Auto-encoder Networks for Cross-view Classification

Abstract:

  The comparison of heterogeneous samples extensively exists in many
applications, especially in the task of image classification. In this paper, we
propose a simple but effective coupled neural network, called Deeply Coupled
Autoencoder Networks (DCAN), which seeks to build two deep neural networks,
coupled with each other in every corresponding layers. In DCAN, each deep
structure is developed via stacking multiple discriminative coupled
auto-encoders, a denoising auto-encoder trained with maximum margin criterion
consisting of intra-class compactness and inter-class penalty. This single
layer component makes our model simultaneously preserve the local consistency
and enhance its discrimin

Distance: 0.875052
====================================================================================================
Rank: 3

Title:

Improving Deep Neural Networks with Probabilistic Maxout Units

Abstract:

  We present a probabilistic variant of the recently introduced maxout unit.
The success of deep neural networks utilizing maxout can partly be attributed
to favorable performance under dropout, when compared to rectified linear
units. It however also depends on the fact that each maxout unit performs a
pooling operation over a group of linear transformations and is thus partially
invariant to changes in its input. Starting from this observation we ask the
question: Can the desirable properties of maxout units be preserved while
improving their invariance properties ? We argue that our probabilistic maxout
(probout) units successfully achieve this balance. We quantitatively verify
this claim

Distance: 0.8914454
====================================================================================================
Rank: 4

Title:

Learning Invariant Representations with Local Transformations

Abstract:

  Learning invariant representations is an important problem in machine
learning and pattern recognition. In this paper, we present a novel framework
of transformation-invariant feature learning by incorporating linear
transformations into the feature learning algorithms. For example, we present
the transformation-invariant restricted Boltzmann machine that compactly
represents data by its weights and their transformations, which achieves
invariance of the feature representation via probabilistic max pooling. In
addition, we show that our transformation-invariant feature learning framework
can also be extended to other unsupervised learning methods, such as
autoencoders or sparse coding. We

Distance: 0.89462173
====================================================================================================
Rank: 5

Title:

Deep learning for class-generic object detection

Abstract:

  We investigate the use of deep neural networks for the novel task of class
generic object detection. We show that neural networks originally designed for
image recognition can be trained to detect objects within images, regardless of
their class, including objects for which no bounding box labels have been
provided. In addition, we show that bounding box labels yield a 1% performance
increase on the ImageNet recognition challenge.


Distance: 0.9020742

In [ ]:
import transformers
print(transformers.__version__)

5.12.1

In [ ]:
!pip uninstall -y transformers tokenizers
!pip install -q transformers==4.41.2
!pip install -q accelerate
!pip install -q sentencepiece

Found existing installation: transformers 4.41.2
Uninstalling transformers-4.41.2:
  Successfully uninstalled transformers-4.41.2
Found existing installation: tokenizers 0.19.1
Uninstalling tokenizers-0.19.1:
  Successfully uninstalled tokenizers-0.19.1

In [ ]:
def recommend(title):

    index_title = df[df["title"]==title].index[0]

    query = embeddings[index_title].reshape(1,-1)

    D,I = index.search(query,6)

    for idx in I[0][1:]:

        print("="*80)

        print(df.iloc[idx]["title"])

In [ ]:
def recommend(title):

    index_title = df[df["title"]==title].index[0]

    query = embeddings[index_title].reshape(1,-1)

    D,I = index.search(query,6)

    for idx in I[0][1:]:

        print("="*80)

        print(df.iloc[idx]["title"])

In [ ]:
recommend(df.iloc[100]["title"])

================================================================================
Copula-based Kernel Dependency Measures
================================================================================
Speedy Model Selection (SMS) for Copula Models
================================================================================
Inference, Sampling, and Learning in Copula Cumulative Distribution
  Networks
================================================================================
Flexible sampling of discrete data correlations without the marginal
  distributions
================================================================================
Inference-less Density Estimation using Copula Bayesian Networks

In [ ]:
!pip uninstall -y transformers tokenizers
!pip install -q transformers==4.41.2
!pip install -q accelerate sentencepiece

Found existing installation: transformers 5.12.1
Uninstalling transformers-5.12.1:
  Successfully uninstalled transformers-5.12.1
Found existing installation: tokenizers 0.22.2
Uninstalling tokenizers-0.22.2:
  Successfully uninstalled tokenizers-0.22.2
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 62.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 36.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 92.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 6.19.0 requires huggingface-hub<2.0,>=1.2.0, but you have huggingface-hub 0.36.2 which is incompatible.

In [ ]:
import transformers
print(transformers.__version__)

4.41.2

In [ ]:
from transformers import pipeline
import torch

device = 0 if torch.cuda.is_available() else -1

summarizer = pipeline(
    "summarization",
    model="sshleifer/distilbart-cnn-12-6",
    device=device
)

print("✅ Summarizer Loaded Successfully!")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.22G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

✅ Summarizer Loaded Successfully!

In [ ]:
text = """
Artificial Intelligence is transforming healthcare by enabling disease prediction,
medical image analysis, and personalized treatment recommendations.
Deep learning models help doctors make faster and more accurate decisions.
"""

summary = summarizer(
    text,
    max_length=50,
    min_length=20,
    do_sample=False
)

print(summary[0]["summary_text"])

Your max_length is set to 50, but your input_length is only 39. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=19)

 Artificial Intelligence is transforming healthcare by enabling disease prediction, medical image analysis, and personalized treatment recommendations . Deep learning models help doctors make faster and more accurate decisions .